<?xml version="1.0" encoding="utf-8"?><Database Name="DKHP" Class="DKHPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KHKHKH\SQLEXPRESS;Initial Catalog=DKHP;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="DKHPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DieuKienMon" Member="DieuKienMons">
    <Type Name="DieuKienMon">
      <Column Name="maDKM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maMHTruoc" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="maMH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="MonHoc_DieuKienMon" Member="MonHoc" ThisKey="maMH" OtherKey="maMH" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongBao" Member="ThongBaos">
    <Type Name="ThongBao">
      <Column Name="maThongBao" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="chuDe" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien" Member="GiangViens">
    <Type Name="GiangVien">
      <Column Name="maGV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hotenGV" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="nganh" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="khoa" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="GiangVien_LopHocPhan" Member="LopHocPhans" ThisKey="maGV" OtherKey="maGV" Type="LopHocPhan" />
    </Type>
  </Table>
  <Table Name="dbo.HocKy" Member="HocKies">
    <Type Name="HocKy">
      <Column Name="maHK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hocKy" Member="hocKy1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NamHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HocKy_LopHocPhan" Member="LopHocPhans" ThisKey="maHK" OtherKey="maHK" Type="LopHocPhan" />
      <Association Name="HocKy_MonHoc" Member="MonHocs" ThisKey="maHK" OtherKey="MaHK" Type="MonHoc" />
    </Type>
  </Table>
  <Table Name="dbo.LopHocPhan" Member="LopHocPhans">
    <Type Name="LopHocPhan">
      <Column Name="maLopHP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maMH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="maHK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenLop" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="maGV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhongHoc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LichHoc" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ThoiGianBDHoc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LopHocPhan_SinhVienDangKy" Member="SinhVienDangKies" ThisKey="maLopHP" OtherKey="maLopHP" Type="SinhVienDangKy" />
      <Association Name="GiangVien_LopHocPhan" Member="GiangVien" ThisKey="maGV" OtherKey="maGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="HocKy_LopHocPhan" Member="HocKy" ThisKey="maHK" OtherKey="maHK" Type="HocKy" IsForeignKey="true" />
      <Association Name="MonHoc_LopHocPhan" Member="MonHoc" ThisKey="maMH" OtherKey="maMH" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="maMH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenMon" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tinChi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lyThuyet" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="thucHanh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Association Name="MonHoc_DieuKienMon" Member="DieuKienMons" ThisKey="maMH" OtherKey="maMH" Type="DieuKienMon" />
      <Association Name="MonHoc_LopHocPhan" Member="LopHocPhans" ThisKey="maMH" OtherKey="maMH" Type="LopHocPhan" />
      <Association Name="HocKy_MonHoc" Member="HocKy" ThisKey="MaHK" OtherKey="maHK" Type="HocKy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="maSV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hotenSV" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="lop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="khoa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="nganh" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NamVaoHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SinhVien_SinhVienDangKy" Member="SinhVienDangKies" ThisKey="maSV" OtherKey="maSV" Type="SinhVienDangKy" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVienDangKy" Member="SinhVienDangKies">
    <Type Name="SinhVienDangKy">
      <Column Name="maSVDangKy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maSV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maLopHP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThuongKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiuaKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuoiKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LopHocPhan_SinhVienDangKy" Member="LopHocPhan" ThisKey="maLopHP" OtherKey="maLopHP" Type="LopHocPhan" IsForeignKey="true" />
      <Association Name="SinhVien_SinhVienDangKy" Member="SinhVien" ThisKey="maSV" OtherKey="maSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="maTK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="quyentruycap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>